# Header

menu:
  主页: /
  归档: /archives/index.html
  随笔: /tags/essays
  算法题: /categories/算法
  java成长路线: /base

# SubNav
subnav:
  github: "https://github.com/sick-cat"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=1392522334&site=qq&menu=yes"
  #weixin: "#"
  jianshu: "https://www.jianshu.com/u/256d795dfcf5"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:j_loser@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '阅读全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢支持'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/txpay.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /img/favicon.png

#你的头像url
avatar: /img/head.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: 'sick-cat'     #你的 GitHub ID
gitment_repo: 'sick-cat.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: '2258b2b846d866f677f9'           #client ID
  client_secret: '4993de220a7d7849446b3ceb90aea004ce18e935'       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#DCDCDC,#D2B48C)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

#是否开启访客数量统计功能
counter: true

# 是否开启访问量统计功能(不蒜子)
busuanzi:
  enable: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  # friends: '友链'
  aboutme: '关于我'

# friends:
#   友情链接1: http://localhost:4000/
#   友情链接2: http://localhost:4000/


aboutme: sick cat<br>我还很菜<br>正在努力奔跑

#版权
declare: true
#作者
author: sick-cat
# 版权基础设定：0-关闭声明； 1-文章对应的md文件里有declare: true属性，才有版权声明； 2-所有文章均有版权声明
declare_type: 2
# 当前应用的版权协议地址。
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
# 版权协议的名称
licensee_name: 'CC BY-NC-SA 4.0'
# 版权协议的Logo
licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png